config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  
  root 'sessions#index'
#  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  helper_method :current_user
#  
#  private
#  
#  def current_user
#    @current_user ||= User.find(session[:user_id]) if session[:user_id]
#  end
  
  protect_from_forgery
  
    def login_required
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      else
        redirect_to root_path
      end
  
    end
  
    helper_method :current_user
  
    private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#  def create
#    auth = request.env["omniauth.auth"]
#    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
#    session[:user_id] = user.id
#    redirect_to root_url, :notice => "Signed in!"
#  end
#  
#  def destroy
#    session[:user_id] = nil
#    redirect_to root_url, :notice => "Signed out!"
#  end
  def callback
      auth = request.env['omniauth.auth']
      user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
      session[:user_id] = user.id
      redirect_to root_path
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ブログのブログ" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "投稿", "/posts/new"  %></li>
            <li><%= link_to "記事一覧", "/posts"  %></li>
            <li>
            	<% if current_user %>
            		<%= link_to 'ログアウト', logout_path %>
            	<% else %>
					<%= link_to "Twitterからログイン", "/auth/twitter" %>
				<% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
	
	<% if current_user %>
	    <div class="container">
	      <div class="row">
	        <div class="col-lg-9">
	          <%= bootstrap_flash %>
	          <%= yield %>
	        </div>
	        <div class="col-lg-3">
	          <div class="well sidebar-nav">
	            <h3>Menu</h3>
	            <ul class="nav nav-list">
	              <li><%= link_to "新しい記事を投稿する", "/posts/new"  %></li>
	              <li><%= link_to "記事一覧を閲覧する", "/posts"  %></li>
	            </ul>
	          </div><!--/.well -->
	        </div><!--/span-->
	      </div><!--/row-->
	<% else %>
		<div class="container">
		      <div class="row">
		        <div class="col-lg-9">
		          <%= bootstrap_flash %>
		          <%= yield %>
		        </div>
		      	<div class="col-lg-3">
	          		<div class="well sidebar-nav">
						<h2>ブログをはじめませんか？</h2>
						<h3><%= link_to "はじめるならここから", "/auth/twitter" %></h3>
						<p>※当ブログを使用するに当たり、Twitterアカウントが必要となります.</p>
					</div>
				</div>
			</div>
		</div>
	<% end %>

		<div class="navbar navbar-default navbar-fixed-bottom">
      		<footer>
      		  <p>&copy; TakashiMiki 2014</p>
     		 </footer>
     	</div>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @post.errors.any? %>
    <div class="form-group" error_explanation">
      <h2>入力誤り<%= @post.errors.count %>件</h2>
      <p>誤りを下記に表示します</p>

      <ul class="nav nav-list">
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :タイトル：, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :内容：, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, cols: 60, rows: 8, :class => 'form-control' %>
    </div>
  </div>


  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            posts_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>記事一覧</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:タイトル) %></th>

      <th><%= model_class.human_attribute_name(:内容) %></th>

      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>

        <td><%= post.text %></td>

        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :syuusei  => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '削除してよろしいですか?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <!-- <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->
  <h1>新しい記事を投稿する</h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <!-- <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1> -->
  <h1>記事を閲覧する</h1>
</div>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>

  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @post.text %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '?')) },
              :class => 'btn btn-danger' %>